SIVAKUMAR PALANIRAJAN

Question 1:
Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 * C * D)/H]
Following are the fixed values of C and H:
C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated
sequence.
Example
Let us assume the following comma separated input sequence is given to the program:
100,150,180
The output of the program should be:
18,22,24

In [6]:
import math
c=50
h=30
a=[]
inputs=list(map(int,input().split(",")))
print(f"The inputs are:{inputs}")
for d in inputs:
    q=math.sqrt((2*c*d)/h)
    a.append(round(q))
print(f"Output:{a}")

The inputs are:[100, 150, 180]
Output:[18, 22, 24]


Question 2:
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The
element value in the i-th row and j-th column of the array should be i*j.
Note: i=0,1.., X-1; j=0,1,¡Y-1.
Example
Suppose the following inputs are given to the program:
3,5
Then, the output of the program should be:
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [4]:
import numpy as np
x=int(input())
y=int(input())
arr=np.zeros((x,y))
for i in range(0,x):
    for j in range(0,y):
        arr[i][j]=i*j
print(np.array(arr))


[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


Question 3:
Write a program that accepts a comma separated sequence of words as input and prints the
words in a comma-separated sequence after sorting them alphabetically.
Suppose the following input is supplied to the program:
without,hello,bag,world
Then, the output should be:
bag,hello,without,world

In [8]:
a=list(input().split(','))
print(f"Intially:{a}")
a.sort()
print(f"After sorting:{a}")

Intially:['without', 'hello', 'bag', 'world']
After sorting:['bag', 'hello', 'without', 'world']


Question 4:
Write a program that accepts a sequence of whitespace separated words as input and prints
the words after removing all duplicate words and sorting them alphanumerically.
Suppose the following input is supplied to the program:
hello world and practice makes perfect and hello world again
Then, the output should be:
again and hello makes perfect practice world

In [21]:
a=list(input().split(" "))
print(f"Before removing duplicates:")
print(*a)
for i in a:
    if a.count(i)>1:
        a.remove(i)
print("After removing duplicates:")
print(*a)

Before removing duplicates:
hello world and practice makes perfect and hello world again
After removing duplicates:
practice makes perfect and hello world again


Question 5:
Write a program that accepts a sentence and calculate the number of letters and digits.
Suppose the following input is supplied to the program:
hello world! 123
Then, the output should be:
LETTERS 10
DIGITS 3

In [23]:
a=input()
n=len(a)
alp=0
num=0
for i in a:
    if i.isalpha():
        alp+=1
    elif i.isnumeric():
        num+=1
    else:
        continue
print(f"The inputs:{a}")
print(f"LETTERS {alp}")
print(f"DIGITS {num}")

The inputs:hello world! 123
LETTERS 10
DIGITS 3


Question 6:
A website requires the users to input username and password to register. Write a program to
check the validity of password input by users.
Following are the criteria for checking the password:
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12
Your program should accept a sequence of comma separated passwords and will check them
according to the above criteria. Passwords that match the criteria are to be printed, each
separated by a comma.
Example
If the following passwords are given as input to the program:
ABd1234@1,a F1#,2w3E*,2We3345
Then, the output of the program should be:
ABd1234@1

In [38]:
a=list(input().split(","))
print("Inputs:")
print(*a,sep=',')
b=[]
for i in a:
    upper=False
    lower=False
    num=False
    spec=False
    qualify=False
    for j in i:
        if len(i)>=6 and len(i)<=12:   
            if j.isalpha():
                if j.isupper():
                    upper=True
                elif j.islower():
                    lower=True
            elif j.isnumeric():
                num=True
            elif j in ['$','#','@']:
                spec=True
    if (spec==True and upper==True and lower==True and num==True):
        b.append(i)
print("Valid Passwords:")
print(*b,sep=",")      

Inputs:
ABd1234@1,a F1#,2w3E*,2We3345
Valid Passwords:
ABd1234@1
